

module.exports = {
    CLIENTES: 'CLIENTES',
    CLIENTES_SUCURSALES: 'CLIENTES_SUCURSALES',
    MONEDAS: 'MONEDAS',
    CODIGOS_POSTALES: 'CODIGOS_POSTALES',
    ESTADOS: 'ESTADOS',
    ZONAS_IVAS: 'ZONAS_IVAS',
    TIPOS_MOVIMIENTOS_DEVOLUCIONS: 'TIPOS_MOVIMIENTOS_DEVOLUCIONS'
}